spring.application.name=restful
spring.jackson.deserialization.fail-on-null-for-primitives=false

# Путь к БД
spring.datasource.url=jdbc:h2:file:./testdb
# Включить консоль СУБД
spring.h2.console.enabled=true

# Настройки Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Стратегия управления БД
spring.jpa.hibernate.ddl-auto=update
